- assets/js/members.js
- members/index.html
- Make the form a proper `<form>` so the Enter key submits.
- Add a loading message.
- Close a `<div>` tag.
> Minor tweaks to the point checker UI.

- chictech/index.html
> Added registration form now that registration is open

- assets/js/techteam.js
- index.html
- techteam/index.html
removed resources from academic page, deprecated academic page and added resources to tech team instead
> Updated Tech Team page with project resources

- assets/js/techteam.js
- techteam/index.html
> updated links on the Tech Team page

- assets/js/mentoring.js
- assets/js/techteam.js
- mentoring/index.html
No big visible changes, just an extra list item to the lists we already have.
> retemplated mentoring, added the projects ppt

- assets/js/techteam.js
Just another bullet to the tutorials list
> added the latest tutorial (data) to tech team

- assets/js/techteam.js
> added submit project form to Tech Team

- chictech/index.html
Added line to say that the registration deadline is extended.
> Registration extended

- assets/js/techteam.js
for the angular lightning talk we did today
> added another team tech entry

- academic/index.html
- alumni/index.html
- assets/css/style.css
- assets/sass/_officers.scss
- chictech/index.html
- index.html
- members/index.html
- mentoring/index.html
- outreach/index.html
- techteam/index.html
> Font fixes, cursors, and getting rid of Ask Me About

- assets/js/techteam.js
> added chrome extension info

- assets/js/officers.js
> Changed Sujay's Title

- assets/js/officers.js
> Added Sujay's Newest Job

- assets/js/alumni.js
- assets/js/officers.js
> Removed console logs

- assets/css/style.css
- assets/sass/_sponsors.scss
- index.html
+added hyperlinks to sponsor images
> Sponsors hyperlinked but broken

- assets/css/style.css
- assets/sass/_variables.scss
- index.html
> Changed the font

- assets/css/style.css
- assets/js/officers.json
- index.html
- sponsors/index.html
> added sponsor folder with its index.html

- assets/js/officers.js
- officers/index.html
Everything seems to work except for the dialog box that pops up when you click on each officer's picture.
> officers subpage

- assets/css/style.css
> Fixed Issue#95

- assets/css/style.css
- assets/sass/_home.scss
- assets/sass/_members.scss
- index.html
- members/index.html
- officers/index.html
- sponsors/index.html
yes Sujay you can merge this one
> fixed a bunch of things

- assets/css/style.css
- officers/index.html
made experiences into button format, changed hobbies out of button form, changed color of buttons
> changed styling of buttons and order of info for officer bio

- assets/css/style.css
- index.html
- officers/index.html
- sponsors/index.html
added body ids to resources and sponsors pages which hopefully fixes the hamburger
> Hamburger button

- alumni/index.html
- assets/js/alumni.json
- assets/js/chictech.js
- assets/js/mentoring.js
- assets/js/resources.js
- assets/js/techteam.js
- chictech/index.html
- contact/index.html
- index.html
- members/index.html
- mentoring/index.html
- officers/index.html
- outreach/index.html
- resources/index.html
- sponsors/index.html
- techteam/index.html
-actually fixed hamburger button
-changed all file paths to relative
-deleted duplicate alum lanaya
> Modify html

- explorations/index.html
Updating with the "dive into technical interviews" workshops and titles of future workshops.
> Adding today's and future workshops

- sponsors/index.html
Made sponsor links the same as images & opens in new tabs
> Update sponsor links

- assets/css/style.css
- assets/js/script.js
Keep the Explore CS flyer proportional when zooming or resizing browser.
Many links in "Upcoming Events" locations clickable.
> Explore flyer proportions & clickable links in upcoming events

- explorations/index.html
Adding database workshop resources & renaming frontend workshop
> Updating explorations page 3/15

- explorations/index.html
> updating explorations workshop 3/19

- explorations/index.html
> Explorations 4/1 update

- explorations/index.html
explorations updates for 4/9 (privacy and security workshop slides & interview workshop info)
> adding updates for 4/9

- explorations/index.html
- explorations/question_box.html
adding the page to host the question box form and any previous questions. we'll probably be making very regular PRs to this site and this is just laying down the framework.
> adding the question box page

- explorations/index.html
- explorations/question_box.html
Adding 4/18 questions and updating the workshop list.
> Question box 4/18

- explorations/question_box.html
adding elizabeth's answer about math+cs transfer
> updating the question box again for this week

- resources/technical.html
Finishing the technical resources page
> Technical resources

- assets/css/sponsors.css
- sponsors/index.html
Add a line to the Sponsors page, "If you are interested in sponsoring us, please email contact@illinoiswcs.org!"
> Add Contact Email to Sponsors Page

- assets/js/committees.json
- committees/index.html
- index.html
* Updated officer names in committee cards
* Updated committee blurbs on committees page and carousel on home page
* Added corporate and infrastructure committees to carousel and committees page
* Alphabetized committees on both pages
* Added note to committees page - Our committee applications open late August!
> Update Committee Information

- components/navbar.html
Took out open office tab from navbar until calendar is finalized.
> Updating Open Office Calendar

- assets/css/home.css
- index.html
Reverts IllinoisWCS/IllinoisWCS.github.io#224
> Revert "Committee Applications Link on Home Page"

- assets/css/home.css
- index.html
> Add applications message and link

- assets/css/home.css
- committees/index.html
- index.html
Remove applications message and link from home page and committees page.
> Remove Applications Message and Link

- assets/css/openoffice.css
- components/navbar.html
- openoffice/index.html
Update the open office calendar with this semester's officer shifts.
Note: Week 2 is the same as Week 1.
> Update Open Office Calendar (Officers Only)

- assets/css/openoffice.css
- assets/js/openoffice.js
- openoffice/index.html
Added this semester's members to the open office calendar
Addresses #239
> Update Open Office Calendar

- src/components/StayInTouchSection.js
- src/components/UpcomingEvent.js
- src/components/UpcomingEventsSection.js
- src/styles/EventsWindow.module.css
- src/styles/Home.module.css
- src/styles/Key.module.css
- src/styles/UpcomingEvent.module.css
:rocket: Ready
Addresses #<number>
Adjusts aspect ratio and scaling of upcoming events
Improves mobile view of Stay In Touch section
Ensures the section headers are positioned according to the figma
Old:
New:
> Adjust styles to closer match Figma

- src/components/NavBarMobile.js
- src/components/navbar.js
- src/styles/Navbar.module.css
- src/styles/NavbarMobile.module.css
Make nav bar mobile responsive with hamburger menu.
Addresses #278
> Mobile NavBar Hamburger Menu

- .eslintrc.json
- package-lock.json
- package.json
- src/pages/resources.js
- src/sections/UpcomingEventsSection.js
- yarn.lock
:rocket: Ready
Add link in Upcoming Events section for members to add WCS GCal to their personal calendars.
> Integrate gcal link to upcoming events

- src/sections/Navbar.js
- src/sections/NavbarMobile.js
- src/styles/sections/CommitteesSection.module.css
- src/styles/sections/Navbar.module.css
- src/styles/sections/NavbarMobile.module.css
:rocket: Ready
Mobile nav dropdown pushes rest of content down the page. Dropdown collapses when navigating to new page. Also fixed committee images not showing up on mobile.
> Mobile nav dropdown fixes and committee images

- src/pages/index.js
- src/sections/Navbar.js
- src/styles/pages/Home.module.css
- src/styles/sections/Navbar.module.css
For chic tech 2024, but can also be used in general for any annoucements
> add the chic tech temp modal

- src/pages/infra.js
> revert branch

- src/components/ExternalOpportunityCategoryCard.js
- src/sections/ExternalOpportunitiesSection.js
- src/styles/components/ExternalOpportunityCategoryCard.module.css
- src/styles/sections/ExternalOpportunitiesSection.module.css
> add external opportunities grid on resources page

- package-lock.json
- src/styles/components/OfficerCard.module.css
> Officer Card Designs

- .github/workflows/nextjs.yml
- package.json
> concurrently for build, .env in workflow

- .eslintrc.json
- .github/workflows/nextjs.yml
- .prettierrc
- .vscode/settings.json
- README.md
- next.config.js
- public/assets/design-vectors/dropdown-arrow.svg
- public/assets/img/favicons/manifest.json
- public/assets/img/favicons/site.webmanifest
- src/pages/resources.js
- src/sections/GetHelpSection.js
- src/styles/components/ComputerWindow.module.css
- src/styles/pages/Resources.module.css
- src/styles/sections/GetHelpSection.module.css
> dropdown arrows + resources header (issue here)

- src/sections/AboutUsSection.js
- src/sections/SponsorsSection.js
- src/styles/sections/Footer.module.css
:rocket: Ready
Put gold tier sponsors on top and bronze on bottom
> Order Sponsors by Tier

- src/styles/globals.css
:rocket: Ready
Changed the font-weight of h3 tags to normal in global styles
Old:
New:
> Lighten Boldness of Navbar text

- src/styles/sections/Navbar.module.css
:rocket: Ready
- Changed hamburger to black to match navbar text color
> Change Hamburger Icon To Black

- src/components/OfficerModal.js
- src/styles/components/OfficerModal.module.css
:rocket: Ready
- make officer modal responsive using media queries
- remove officer image on mobile
- move social media icons up on mobile
> make officer modal responsive

- src/components/StayInTouchKey.js
:rocket: Ready
- window.open could return null, which was causing the error
- added a null check before calling .focus()
> Fix Footer Runtime Error

- package-lock.json
- src/styles/components/EventsWindow.module.css
Addresses: <(link notion task here)>
> moved arrows to buttons

- src/styles/pages/Home.module.css
:rocket: Ready
- added negative bottom margin for sponsors section
> Shift Up Binary SVG on Home Page

- src/pages/_document.js
- src/pages/resources.js
- src/pages/team.js
- src/sections/AboutUsSection.js
- src/sections/UpcomingEventsSection.js
- src/styles/globals.css
- src/styles/pages/404.module.css
- src/styles/pages/Resources.module.css
- src/styles/pages/Team.module.css
- src/styles/sections/AboutUsSection.module.css
:rocket: Ready
- added import statement for nunito and zilla slab
> Update Font Styles

- package-lock.json
- src/styles/pages/Home.module.css
- src/styles/pages/OpenOffice.module.css
- src/styles/sections/GetHelpSection.module.css
:rocket: Ready
Fixed open office committee member font size. Fixed font color for resources get help section. Also fixed the font color for the sponsors section.
> fix resources color and open office font size

- README.md
- src/pages/infra.js
- src/styles/pages/Infra.module.css
> onboarding assignment setup
